# Generated by Django 2.2 on 2023-10-20 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmp', '0002_comprasdet_comprasenc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprasenc',
            old_name='proovedor',
            new_name='proveedor',
        ),
    ]
